name: Sync to Huggingface Hub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to Huggingface Hub
        uses: huggingface/huggingface-cli-action@main
        with:
          token: ${{ secrets.HF_TOKEN }}
          repo_id: <Niruppa2000>/<Text_summarization_chatbot>
